### ISSUE TITLE
Add Wagtail Space 2017 presentations

### ISSUE THREAD

**Issue by thibaudcolas** [springload/awesome-wagtail#62]
It would be nice to do the same as #61, but for the Wagtail Space 2017 presentations. Here are the videos to cut:

- https://www.youtube.com/watch?v=-Qii_AyQsxE
- https://www.youtube.com/watch?v=OedQi5W3Zho
- https://www.youtube.com/watch?v=ObM2pUgY-bs
- https://www.youtube.com/watch?v=hZcuq8WJVew

I don't have time to go through this right now unfortunately, but if anyone wants to contribute something to this list this is a good first pick 🙏.

**Comment by loicteixeira** [comment]
It's missing a few names which I couldn't pick up from the audio.

It is mentioned at some point that there is a document linked on Slack with the schedule so I'll try to dig into the archives, but if someone can hear it better than me, please jump in. Edit: Can't quite look that far back in the archives since Wagtail is on the free plan. I asked Four Digits for the file via email.

### Wagtail related

[Wagtail & Agile](https://youtu.be/-Qii_AyQsxE?t=2m21s) by Edd Baldry

[Deploy Wagtail to the Divio Cloud](https://youtu.be/-Qii_AyQsxE?t=38m13s) by Daniele Procida

[All about Wagtail](https://youtu.be/OedQi5W3Zho) by Robin van der Rijst

[Presenting Wagtail Clear StreamField, a modular StreamField app](https://youtu.be/OedQi5W3Zho?t=19m1s) by Edd Baldry

[Wagtail Experiments, easy A/B testing for your Wagtail sites](https://youtu.be/OedQi5W3Zho?t=34m37s) by Tom Dyson

[Wagtail's preview, a new hope](https://www.youtube.com/watch?v=ObM2pUgY-bs) by Bertrand Bordage

[The Zen of Wagtail](https://youtu.be/ObM2pUgY-bs?t=16m38s) by Matt Westcott

[Plone to Wagtail](https://youtu.be/hZcuq8WJVew?t=2m57s) by Coen van der Kamp

[Hundreds of Wagtail in Flight](https://youtu.be/hZcuq8WJVew?t=24m9s) by Simon de Haan

### Other

[Using React with Keystone JS](https://youtu.be/hZcuq8WJVew?t=15m35s) by Lones Kling?

[Building an Open Source Community](https://youtu.be/-Qii_AyQsxE?t=15m16s) by Ben van't Ende

[Loss of Situational Awarness](https://youtu.be/hZcuq8WJVew?t=31m56s) by Daniele Procida

[Call for help](https://youtu.be/hZcuq8WJVew?t=19m21s) by Matthew Donoris from opendemocracy.net has questions regarding whether Wagtail would be a good fit for their platform.

**Comment by thibaudcolas** [comment]
@loicteixeira 👏 the ones I know:

- Wagtail and Agile and Presenting Wagtail Clear StreamField are by https://github.com/heymonkeyriot
- Hundreds of Wagtail in Flight is https://github.com/smn

**Comment by thibaudcolas** [comment]
Maybe @allcaps could help us figure out what Robin's talk was titled?

**Comment by loicteixeira** [comment]
Thanks! Updated.

**Comment by allcaps** [comment]
This is how it was listed on the wagtail space 2017 site:

Current confirmed talks:

Tom Dyson: Wagtail Experiments - easy A/B testing for your Wagtail sites
Mike Dingjan: Wagtailtrans - Support multiple languages for your Wagtail site
Ben van't Ende: Building an Open Source Community
Mike Overkamp: File download counter
Daniele Procida: Deploy Wagtail to the Divio Cloud
Rob Moorman: Static Site
Edd Baldry: Wagtail & Agile
Edd Baldry: Modular StreamField app
Fabrique: All about Wagtail
Matt Wescott: The Zen of Wagtail

Robin is from Fabrique, his talk was: 'All about Wagtail'.

**Comment by loicteixeira** [comment]
Thanks! I've updated the above list accordingly, although I couldn't find those talks on the recordings:

- Mike Overkamp: File download counte
- Rob Moorman: Static Site

**Comment by allcaps** [comment]
Those talks were given, but where - unfortunately - not recorded. 

Mike had the shortest talk ever about his download counter. It counts downloads ;)
https://pypi.python.org/pypi/wagtail-download-counter/0.0.1

@robmoorman Can you provide pointers to your presentation / code?

Lars, Mike and I programmed Eddie, the educational robot. This is the video: https://www.youtube.com/watch?v=-GPbywRWkIU
